alias l='lsd -1AL --group-dirs=first --hyperlink=auto'
alias ls='lsd -AFl --group-dirs=first --hyperlink=auto --permission=octal'
alias lstr='lsd -I.git -I.jj -I.direnv --tree -AFl --group-dirs=first --hyperlink=auto --permission=octal'
alias mv='mv -iv'
alias cp='cp -irv'
alias rm='rm -irv'
alias confedit='e $HOME/nixconfig'
alias c='clear'
alias cat='bat --style=full'
alias cd='z'
alias jjl='jj log -r '\''@ | ancestors(immutable_heads()..) | trunk()'\'' --no-pager --limit=6'
alias jjgf='jj git fetch'
alias upgrade='local zhuktmpdir="$(pwd)"; cd $HOME/nixconfig && nix flake update; cd $zhuktmpdir && unset zhuktmpdir'
alias em='zhukmacs'
alias nv='nvim'
alias tmux="TERM=screen-256color tmux"
